version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://posterr_service:password@db:3306/posterr_db
      FLASK_ENV: production
      APP_PORT: 8000
    working_dir: /src
    depends_on:
      db:
        condition: service_healthy
    command: ["./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    build:
      context: ./db
      args:
        MYSQL_VERSION: 8.0
    environment:
      MYSQL_USER: posterr_service
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: posterr_db
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 1s
      retries: 10


volumes:
  data:
    driver: local
